This notebook performs a high level analysis of the loans in the dataset, primarily from the perspective of assessing financial performance, identifying drivers of defaults and identifying financial targets for the machine learning model. 

Key Statistics
* Default Rate: 19.18% 
* Gains from good loans: ~912m
* Losses from bad loans: ~560m
* Net Gains: ~353m 
* The  loans in the bottom two "grades" are unprofitable overall, with the grade above it barely profitable (i.e. grades E, F, G) 

### What we've learned so far
##### this data is repeated at the bottom of this notebook, but placed here for convenience)
* Removing loans with an interest rate above 13.5% would wipe out about approximately 87M in gains, but increased annualized return on total loans by about 25%. The company would deploy 2.4 billion less in capital, but only earn around 87M less. An argument that Lending Club could find higher yield activities (~1.21% annualized gain) for ~2.4B. Note as if this writing (4/08/22) two year T-Bills are paying 2.51% and they were paying 1.63% a month ago. 
* Removing all loans below Class D barely changes net gains, but increases returns on the loan portfolio by about 15.6%. I.e. the loans below Class D barely broke even, while requiring nearly 1B less in lending funds to generate. 
* On average bad loans wipe out the gains from ~2.6 good loans. Meaning a "false positive" as far as giving a loan that will eventually go into default, is roughly 2.6X more expensive than rejecting a customer who would pay off their loan 
* In a perfect world, the company would earn about 5.9% annualized fromm its lending business, I.e. the loans that were paid in full delivered a 5.9% annnualized return 
* Even though F & G loans constitute only ~2.8% of all loans, the fact that both categories are a net loss means that LC should stop originating loans in this category 
* While we don't know how much it costs to service/manage an individual loan, the low average return (~333) of the loans in class E (8.22% of all loans) + the default rate of 37.9% suggests that the company should stop originating loans in that category as well. I.e. a loan clas with a high default rate suggests that this category is more expensive to manage than say Class A or B loans, meaning, once operational costs are removed from the gains from Class E, the return is probably significantly less than 333.00 


For the purposes of this exercise, "success" will be a model that provides greater value than the two proposed interventions:
* Not originating loans to customers with loan grades below D, meaning: <16.5% default rate, >351M in gains, <5.09B in deployed capital 
* Setting an interest cap at 13.5%, <3.6B in deployed capital, >270M in gains, <10.6% default rate

There are clear options to improve the performance of LC lending portfolio, so for a model to provide business value it would have to outperform one or both of the intervention options identified via the EDA process. I.e. the model would need to provide a 3rd option that is superior to the other two, which are fairly standard banking options: increase your lending standards. 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
from eda_class import EDA
import warnings 
warnings.filterwarnings('ignore')
%matplotlib inline
import xgboost as xgb
from sklearn import linear_model, metrics
from sklearn.model_selection import GridSearchCV 
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
%matplotlib inline
from xgboost import plot_importance
from numpy import mean
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from xgboost import XGBClassifier
warnings.simplefilter(action='ignore', category=FutureWarning)




In [2]:
# set size parameters for the plots 
plt.rcParams['figure.figsize'] = [12, 8]
plt.rcParams['figure.dpi'] = 100 


# set view parameters for the data frames 
pd.options.display.max_rows = 999
pd.options.display.max_columns = 999




In [3]:
# instantiate the EDA functions that will help us analyze the data 

eda_functions = EDA()

In [4]:
# quickly revisit some of the EDA from the prior analysis in order to acquire some data around 
# cost trade offs. I.e. cost of false negative (rejecting a good loan) vs. false positive (rejecting a good loan)

data = pd.read_csv('data/LC_2015_clean(4)_updated_April2022.csv')

# moving the loan status column so the most important columns are all in one place
status_column = data.pop('loan_status')
data.insert(5, 'loan_status', status_column)


data.head(10)

funded_amnt        term  int_rate  installment grade  loan_status  \
0      20000.0   36 months    0.1485       691.84     C   Fully Paid   
1      20000.0   36 months    0.1577       700.88     D   Fully Paid   
2      10000.0   60 months    0.1797       253.78     D  Charged Off   
3      20000.0   36 months    0.0849       631.26     B   Fully Paid   
4      10000.0   36 months    0.0649       306.45     A   Fully Paid   
5       8000.0   36 months    0.1148       263.74     B   Fully Paid   
6      28000.0   36 months    0.0649       858.05     A   Fully Paid   
7      18000.0   60 months    0.1199       400.31     C   Fully Paid   
8       9600.0   36 months    0.0749       298.58     A   Fully Paid   
9      25000.0   36 months    0.0749       777.55     A   Fully Paid   

   emp_length home_ownership  annual_inc verification_status     issue_d  \
0           6           RENT    110000.0        Not Verified  2015-12-01   
1           5           RENT     70000.0        Not Verified  2015-12-01   
2           2       MORTGAGE     55000.0        Not Verified  2015-12-01   
3          10       MORTGAGE     85000.0        Not Verified  2015-12-01   
4           6           RENT     85000.0        Not Verified  2015-12-01   
5          10       MORTGAGE     42000.0        Not Verified  2015-12-01   
6          10       MORTGAGE     92000.0        Not Verified  2015-12-01   
7          10       MORTGAGE    112000.0        Not Verified  2015-12-01   
8           8       MORTGAGE     60000.0        Not Verified  2015-12-01   
9          10       MORTGAGE    109000.0        Not Verified  2015-12-01   

              purpose addr_state    dti  delinq_2yrs earliest_cr_line  \
0         credit_card         IL  12.45          0.0       2007-06-01   
1               house         FL  22.21          0.0       2004-07-01   
2         credit_card         CO  35.70          0.0       2001-04-01   
3      major_purchase         SC  17.61          1.0       1999-02-01   
4         credit_card         PA  13.07          0.0       2002-04-01   
5         credit_card         RI  34.80          0.0       1994-11-01   
6  debt_consolidation         NC  21.60          0.0       1984-05-01   
7  debt_consolidation         AZ   8.68          0.0       1993-11-01   
8         credit_card         SC  22.44          0.0       1996-06-01   
9  debt_consolidation         VA  26.02          0.0       2001-12-01   

   fico_range_low  inq_last_6mths  mths_since_last_delinq  open_acc  pub_rec  \
0           690.0             0.0                     0.0       8.0      0.0   
1           680.0             0.0                    38.0      24.0      0.0   
2           685.0             0.0                     0.0      14.0      0.0   
3           705.0             0.0                     3.0       8.0      0.0   
4           685.0             1.0                     0.0      14.0      1.0   
5           700.0             0.0                    75.0       8.0      0.0   
6           720.0             0.0                    42.0      16.0      0.0   
7           800.0             0.0                     0.0      17.0      0.0   
8           695.0             0.0                     0.0       7.0      0.0   
9           745.0             1.0                     0.0       9.0      0.0   

   pub_rec_bankruptcies  revol_bal  revol_util  total_acc   total_pymnt  \
0                   0.0    21374.0       0.845       12.0  24889.013360   
1                   0.0    19077.0       0.366       63.0  21780.586780   
2                   0.0    38623.0       0.780       28.0   5558.200000   
3                   0.0      826.0       0.057       15.0  21538.508980   
4                   1.0    10464.0       0.345       23.0  10998.971570   
5                   0.0     7034.0       0.391       18.0   8939.580503   
6                   0.0    51507.0       0.645       24.0  29939.017730   
7                   0.0    10711.0       0.155       27.0  18387.220000   
8            

In [5]:
# overall performance 
overall_performance = eda_functions.calc_performance(data)


#default rate
default = eda_functions.categorical_count(data, 'loan_status')

In [6]:
# overall performance
# ~5.9B in total loans vs. 352M in total net gains 

overall_performance.head()

total_loan_value  total_net_gains avg_interest rate avg_loan_amount  \
0     5909868050.0  353343408.02431         12.553595    15307.366478   

  avg_gains($) avg_gains(%) annualized_return  
0    915.20775     5.978871            1.9374

In [7]:
# defaults - default rate is about 19.17% 

default

loan_status   count  per_of_total
0   Fully Paid  312052      0.808257
1  Charged Off   74028      0.191743

In [8]:
# split out two separate datasets for paid vs. defaulted loans 

default_df = data[(data['loan_status'] == 'Charged Off')]
default_losses = default_df['net_gain'].sum()


paid_df = data[(data['loan_status'] == 'Fully Paid')]
paid_gains = paid_df['net_gain'].sum()


In [9]:
# calculate the performance of the good loans

paid_performance = eda_functions.calc_performance(paid_df)
paid_performance

total_loan_value  total_net_gains avg_interest rate avg_loan_amount  \
0     4707936775.0  912922028.77431         11.966344    15087.026441   

  avg_gains($) avg_gains(%) annualized_return  
0  2925.544553    19.391128          5.494593

In [10]:
# calculate the performance of the bad loans 

bad_performance = eda_functions.calc_performance(default_df)
bad_performance


total_loan_value total_net_gains avg_interest rate avg_loan_amount  \
0     1201931275.0   -559578620.75         15.029049    16236.171111   

  avg_gains($) avg_gains(%) annualized_return  
0 -7559.013086   -46.556624        -29.185224

The first item that immediately jumps out is that the average interest rate for defaulted loans is about 25% higher than the rate for loans that were paid off. This is probably most reflective of riskier customers being giving higher interest rates to shield LC against that risk, but given the burden caused by higher interest rates, LC is probably hurting themselves more than they are protecting against risk.The second item is that bad loans are very expensive, despite good loans outnumbering bad loans by nearly 4:1, the bad loans wiped out nearly 2/3rds of the gains from the good loans. I.e. every bad loan wiped out the gains from 2.6 good loans. 

In [11]:
# let's check and see if there are loans that are defaulted, but the person made enough payments
# so that the loan still delivered a positive return 

positive_default = default_df[(default_df['net_gain'] > 0)]

positive_default 



funded_amnt        term  int_rate  installment grade  loan_status  \
16          16000.0   36 months    0.1288       538.18     C  Charged Off   
126         16000.0   36 months    0.1577       560.70     D  Charged Off   
141          5000.0   36 months    0.1199       166.05     C  Charged Off   
151         30000.0   60 months    0.1849       769.83     D  Charged Off   
273         10400.0   36 months    0.1344       352.63     C  Charged Off   
...             ...         ...       ...          ...   ...          ...   
385756       8100.0   36 months    0.1499       280.75     C  Charged Off   
385929      15775.0   60 months    0.1924       411.30     E  Charged Off   
385945      12000.0   36 months    0.1144       395.37     B  Charged Off   
385991      30000.0   36 months    0.1366      1020.39     C  Charged Off   
386014      12900.0   60 months    0.1854       331.38     E  Charged Off   

        emp_length home_ownership  annual_inc verification_status     issue_d  \
16              10       MORTGAGE     65000.0        Not Verified  2015-12-01   
126              1       MORTGAGE     70000.0        Not Verified  2015-12-01   
141              1           RENT     30000.0     Source Verified  2015-12-01   
151              2       MORTGAGE     85000.0     Source Verified  2015-12-01   
273             10       MORTGAGE    150000.0            Verified  2015-12-01   
...            ...            ...         ...                 ...         ...   
385756           4       MORTGAGE     52600.0     Source Verified  2015-01-01   
385929           1            OWN     36000.0        Not Verified  2015-01-01   
385945          10       MORTGAGE    125000.0        Not Verified  2015-01-01   
385991           1       MORTGAGE    120000.0            Verified  2015-01-01   
386014          10            OWN     36000.0     Source Verified  2015-01-01   

                   purpose addr_state    dti  delinq_2yrs earliest_cr_line  \
16          small_business         AL  18.96          0.0       1985-12-01   
126     debt_consolidation         NJ   8.78          0.0       2004-03-01   
141     debt_consolidation         MD   9.16          0.0       2005-04-01   
151     debt_consolidation         NJ  35.93          0.0       2003-10-01   
273     debt_consolidation         MO  18.51          1.0       1991-03-01   
...                    ...        ...    ...          ...              ...   
385756  debt_consolidation         MI  17.70          0.0       1990-05-01   
385929         credit_card         CA  14.23          0.0       2006-10-01   
385945    home_improvement         CA  34.07          0.0       1994-10-01   
385991  debt_consolidation         TX  18.23          0.0       1992-11-01   
386014  debt_consolidation         GA  34.20          0.0       1990-09-01   

        fico_range_low  inq_last_6mths  mths_since_last_delinq  open_acc  \
16               675.0             0.0                    33.0       7.0   
126              705.0             1.0                     0.0       7.0   
141              675.0             0.0                    29.0      12.0   
151              665.0             0.0                    45.0      21.0   
273              670.0             1.0                    22.0      23.0   
...                ...             ...                     ...       ...   
385756           660.0             1.0                    25.0      11.0   
385929           700.0             2.0                    79.0      22.0   
385945           670.0             1.0                    29.0      17.0   
385991           705.0             0.0                     0.0      11.0   
386014           670.0             1.0                     0.0      10.0   

        pub_rec  pub_rec_bankruptcies  revol_bal  revol_util  total_acc  \
16          1.0                   0.0     5157.0       0.543       20.0   
126         0.0                   0.0    15986.0       0.761       25.0   
141         2.0                   0

Given that there were roughly 70k bad loans, the above indicates that a little less than 10% of the bad loans still turned a profit. This suggests that a machine learning model that identified these loans as false positives, wouldn't per se be a bad thing, as the goal is to maximize profits, not just reduce the default rate. 

In [12]:
# LC groups loans by grade, how does the performance of the loans look within those grades?


grade_analysis = data[['int_rate', 'net_gain', 'loan_status', 'fico_range_low','grade', 
                       'monthly_debt_payments', 
                       'countdown_zero_delinq','annual_inc',
                       'monthly_income', 'dti_dec', 'post_loan_dti']]


# convert loan status to dummy variables so we have a column for paid and a column for default
# with boolean yes/no variables as 1s and 0s 
grade_performance = pd.get_dummies(grade_analysis, columns = ['loan_status'])

# update the column names 
grade_performance.rename(columns={'loan_status_Charged Off':'default'}, inplace = True)
grade_performance.rename(columns={'loan_status_Fully Paid':'paid'}, inplace = True)


grade_performance = grade_performance.groupby('grade').mean()

grade_performance.reset_index(inplace = True)

default_col = grade_performance.pop('default')
grade_performance.insert(1, 'default_rate', default_col)

grade_performance.head(7)



grade  default_rate  int_rate     net_gain  fico_range_low  \
0     A      0.053517  0.069413  1013.090019      719.340537   
1     B      0.122960  0.100430  1140.228640      694.785282   
2     C      0.209486  0.132971  1059.093132      686.500232   
3     D      0.298315  0.167231   756.907693      682.838034   
4     E      0.378653  0.192983   337.293011      681.936256   
5     F      0.465843  0.236242  -740.637748      680.649755   
6     G      0.505226  0.268314 -1449.532723      679.168741   

   monthly_debt_payments  countdown_zero_delinq    annual_inc  monthly_income  \
0            1163.548274             -21.071690  92904.659333     7742.054944   
1            1123.354834             -26.838001  80390.292756     6699.191063   
2            1126.853860             -26.982221  73907.382085     6158.948507   
3            1153.083213             -26.799308  69925.417166     5827.118097   
4            1202.351869             -26.706381  72090.865136     6007.572095   
5            1206.732995             -26.962951  72888.933013     6074.077751   
6            1112.846800             -28.800398  71157.650582     5929.804215   

    dti_dec  post_loan_dti      paid  
0  0.162396       0.229110  0.946483  
1  0.179610       0.250233  0.877040  
2  0.196116       0.274171  0.790514  
3  0.213271       0.303537  0.701685  
4  0.216452       0.315093  0.621347  
5  0.213880       0.323252  0.534157  
6  0.201376       0.320982  0.494774

In [13]:
# let's see how many loans are originated in each category 
# access the categorical count function to get a count of each category + calculate 
# percentage of total.

grade_count = eda_functions.categorical_count(data, 'grade')

# extract the default rate column and the grade column, so we can add the default rates per 
# grade to the grade count data frame 

grade_default = grade_performance[['grade', 'default_rate']]


# use a join to add the default column to the grade count data frame 
grade_count = pd.merge(grade_count, grade_default, on='grade')


# calculate the number of defaulted loans 
grade_count['default_count'] = grade_count['count'] * grade_count['default_rate']

# calculate total number of defaulted loans 
total_defaults = grade_count['default_count'].sum()

grade_count['default_per_of_total'] = grade_count['default_count']/total_defaults



grade_count.head(7)


grade   count  per_of_total  default_rate  default_count  \
0     C  109683      0.284094      0.209486        22977.0   
1     B  108328      0.280584      0.122960        13320.0   
2     A   68950      0.178590      0.053517         3690.0   
3     D   56370      0.146006      0.298315        16816.0   
4     E   31752      0.082242      0.378653        12023.0   
5     F    8988      0.023280      0.465843         4187.0   
6     G    2009      0.005204      0.505226         1015.0   

   default_per_of_total  
0              0.310383  
1              0.179932  
2              0.049846  
3              0.227157  
4              0.162412  
5              0.056560  
6              0.013711

Looking at the data so far, it's fairly obvious that the company should stop originating grade F and G loans, and given the small gains and high default rates should stop originating E loans as well, as the overhead and serving costs undoubtedly erase a significant portion of the small amount of gains from that class. What would performance look like if we removed those loans? 



In [14]:
top_grades =  (data[(data['grade'] == 'A') | (data['grade'] == 'B') | (data['grade'] == 'C') |\
                    (data['grade'] == 'D')])

top_performance = eda_functions.calc_performance(top_grades)

top_performance.head()



total_loan_value  total_net_gains avg_interest rate avg_loan_amount  \
0     5094368475.0  352202643.64421         11.556468    14838.067273   

  avg_gains($) avg_gains(%) annualized_return  
0  1025.839914     6.913568          2.230594

In [15]:
#default rate
default_top_grades = eda_functions.categorical_count(top_grades, 'loan_status')

default_top_grades

loan_status   count  per_of_total
0   Fully Paid  286528      0.834553
1  Charged Off   56803      0.165447

Getting rid of loans below class D results in roughly 900M in loans being taken off the table, but a reduction in profit of barely 1M, but an increase in annualized returns of ~15.6%. In other words, the return from the loans that would no longer be originated was roughly 0.11%. 

In [16]:
# as a comparison, what would happen if instead of no longer originating loans in classes E, F and G, 
# the company were to instead set an interest rate cap, since interest rates and chances of default
# are highly correlated? 

rate_cap = data[(data['int_rate'] <= 0.135)]

cap_performance = eda_functions.calc_performance(rate_cap)

cap_performance

total_loan_value   total_net_gains avg_interest rate avg_loan_amount  \
0     3551611025.0  266735565.154124          9.908338     14495.18825   

  avg_gains($) avg_gains(%) annualized_return  
0  1088.627725      7.51027          2.421427

In [17]:
#default rate
default_rate_cap = eda_functions.categorical_count(rate_cap, 'loan_status')
default_rate_cap

loan_status   count  per_of_total
0   Fully Paid  214927      0.877181
1  Charged Off   30093      0.122819

### What we've learned so far:
* Removing loans with an interest rate above 13.5% would wipe out about approximately 87M in gains, but increased annualized return on total loans by about 25%. The company would deploy 2.4 billion less in capital, but only earn around 87M less. An argument that Lending Club could find higher yield activities (~1.21% annualized gain) for ~2.4B. Note as if this writing (4/08/22) two year T-Bills are paying 2.51% and they were paying 1.63% a month ago. 
* Removing all loans below Class D barely changes net gains, but increases returns on the loan portfolio by about 15.6%. I.e. the loans below Class D barely broke even, while requiring nearly 1B less in lending funds to generate. 
* On average bad loans wipe out the gains from ~2.6 good loans. Meaning a "false positive" as far as giving a loan that will eventually go into default, is roughly 2.6X more expensive than rejecting a customer who would pay off their loan 
* In a perfect world, the company would earn about 5.9% annualized fromm its lending business, I.e. the loans that were paid in full delivered a 5.9% annnualized return 
* Even though F & G loans constitute only ~2.8% of all loans, the fact that both categories are a net loss means that LC should stop originating loans in this category 
* While we don't know how much it costs to service/manage an individual loan, the low average return (~333) of the loans in class E (8.22% of all loans) + the default rate of 37.9% suggests that the company should stop originating loans in that category as well. I.e. a loan clas with a high default rate suggests that this category is more expensive to manage than say Class A or B loans, meaning, once operational costs are removed from the gains from Class E, the return is probably significantly less than 333.00 


For the purposes of this exercise, "success" will be a model that provides greater value than the two proposed interventions:
* Not originating loans to customers with loan grades below D, meaning: <16.5% default rate, >351M in gains, <5.09B in deployed capital 
* Setting an interest cap at 13.5%, <3.6B in deployed capital, >270M in gains, <10.6% default rate

There are clear options to improve the performance of LC lending portfolio, so for a model to provide business value it would have to outperform one or both of the intervention options identified via the EDA process. I.e. the model would need to provide a 3rd option that is superior to the other two, which are fairly standard banking options: increase your lending standards. 
